### PR TITLE
build(Jenkinsfile): Add Jenkinsfile to enable CI

### PR DESCRIPTION
**Pull request by lenny-intel**
Jenkinsfile added to enable CI

Addresses #1 and https://github.com/edgexfoundry/ci-management/issues/484

### CODE REVIEW

**Comment by lranjbar** [comment]
@soda480 Emilio is working on this one.

**Comment by jamesrgregg** [comment]
This PR should reference the Issue for the new build automation.
https://github.com/orgs/edgexfoundry/projects/18

**Comment by soda480** [comment]
I submitted the following request to LF to have the respective settings files created for device-rest-go: [IT-18701](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-18701). Probably best to wait until the settings file are there before we merge.

**Comment by soda480** [comment]
https://github.com/edgexfoundry/device-rest-go/pull/9

**Comment by lenny-intel** [comment]
> Preferably close this and let us work through the changes in #9

Done.

**Pull request closed without merging**
