### PR TITLE
fix: update device resource RW permission to read-only

### LINKED ISSUE #136: The sample profile should contain read permission not write permission
Currently, the device resources in the sample profiles are `W` (write only).
https://github.com/edgexfoundry/device-rest-go/blob/8988443161b762d02568202c1b71a3f56b05d0c9/cmd/res/profiles/sample-image-device.yaml#L9-L23

It should be `R` (read only) according to the original v1 profile samples.
https://github.com/edgexfoundry/device-rest-go/blob/9e4888f50a2a312870744f4f89808877d999d7c6/cmd/res/sample-json-device.yaml#L18-L21
https://github.com/edgexfoundry/device-rest-go/blob/9e4888f50a2a312870744f4f89808877d999d7c6/cmd/res/sample-numeric-device.yaml#L26-L32
https://github.com/edgexfoundry/device-rest-go/blob/9e4888f50a2a312870744f4f89808877d999d7c6/cmd/res/sample-image-device.yaml#L25-L31

In addition, we don't support any write command for binary data type for now.

### PR DESCRIPTION
**Pull request by chr1shung**
fix #136 

Signed-off-by: Chris Hung <chris@iotechsys.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rest-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Review by lenny-intel — APPROVED** [review]

**Pull request merged**
