### PR TITLE
fix(build): update to go 1.16

### PR DESCRIPTION
**Pull request by tonyespy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rest-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
This PR updates the service to use go 1.16 (including the snap build), and also fixes a snap build breakage caused by recent build changes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by lenny-intel — CHANGES_REQUESTED** [review]
The 2 Dockerfiles also need to be updated

**Comment by tonyespy** [comment]
> The 2 Dockerfiles also need to be updated

Done and pushed...

**Comment by cloudxxx8** [comment]
the docker images of all other services are still alpine:3.12
we can decide whether we should upgrade to 3.13 for all

**Comment by tonyespy** [comment]
> the docker images of all other services are still alpine:3.12
> we can decide whether we should upgrade to 3.13 for all

I just force-pushed to revert the 3.13 change. I missed the fact that there was an alpine 3.12 tag for go 1.16.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
